### ISSUE TITLE
IndentationError: expected an indented block

### ISSUE THREAD

**Issue by senselessDev** [miguelmota/py-etherdelta#1]
https://github.com/miguelmota/py-etherdelta/blob/dbee60bd4b186b14e14f0623a7f0ecc8b7ea0f0d/etherdelta/__init__.py#L381-L382

comment out else or uncomment print. Otherwise, "IndentationError: expected an indented block" will be raised.

**Comment by miguelmota** [comment]
thanks for reporting. fixed in https://github.com/miguelmota/py-etherdelta/commit/57886ee26ea38b6c509715bf4fe7d8a7944fc5fd#diff-5fb998dc576ee9ff08b821f91388ec3aL381
